INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(120, 'Charizard', 'Flame Pokémon from Base Set', 'Fire Spin', '100', 'Water', NULL, '3', 4, 1, 1, 3),
(60, 'Pikachu', 'Electric Mouse Pokémon from Jungle', 'Thunder Jolt', '30', 'Fighting', 'Metal', '1', 27, 2, 4, 1),
(90, 'Lapras', 'Water Pokémon from Fossil', 'Water Gun', '30+', 'Electric', NULL, '2', 10, 3, 2, 1),
(70, 'Jigglypuff', 'Balloon Pokémon from Jungle', 'Lullaby', '0', 'Fighting', 'Psychic', '1', 54, 2, 10, 1),
(130, 'Gengar', 'Shadow Pokémon from Fossil', 'Nightmare', '30', 'Darkness', 'Fighting', '2', 5, 3, 5, 3),
(100, 'Blastoise', 'Shellfish Pokémon from Base Set', 'Hydro Pump', '60+', 'Electric', NULL, '3', 2, 1, 2, 3),
(80, 'Venusaur', 'Seed Pokémon from Base Set', 'Solar Beam', '60', 'Fire', NULL, '2', 15, 1, 3, 3),
(50, 'Eevee', 'Evolution Pokémon from Jungle', 'Quick Attack', '20+', 'Fighting', NULL, '1', 55, 2, 10, 1),
(70, 'Meowth', 'Scratch Cat Pokémon from Jungle', 'Pay Day', '20', 'Fighting', NULL, '1', 56, 2, 10, 1),
(110, 'Snorlax', 'Sleeping Pokémon from Jungle', 'Body Slam', '30', 'Fighting', NULL, '4', 11, 2, 10, 1),
(60, 'Cubone', 'Lonely Pokémon from Fossil', 'Bone Attack', '30', 'Grass', NULL, '1', 50, 3, 6, 1),
(90, 'Hitmonlee', 'Kicking Pokémon from Fossil', 'Stretch Kick', '40', 'Psychic', NULL, '2', 7, 3, 6, 1),
(100, 'Aerodactyl', 'Fossil Pokémon from Fossil', 'Wing Attack', '30', 'Water', NULL, '2', 1, 3, 9, 2),
(70, 'Magneton', 'Magnet Pokémon from Base Set', 'Thunder Wave', '30', 'Fighting', NULL, '2', 9, 1, 8, 2),
(60, 'Abra', 'Psi Pokémon from Base Set', 'Psyshock', '10', 'Psychic', NULL, '1', 43, 1, 5, 1),
(80, 'Kadabra', 'Psi Pokémon from Base Set', 'Recover', '30', 'Psychic', NULL, '2', 34, 1, 5, 2),
(100, 'Alakazam', 'Psi Pokémon from Base Set', 'Confuse Ray', '30', 'Psychic', NULL, '3', 1, 1, 5, 3),
(70, 'Scyther', 'Mantis Pokémon from Jungle', 'Slash', '30', 'Fire', NULL, '1', 10, 2, 3, 1),
(60, 'Electabuzz', 'Electric Pokémon from Base Set', 'Thunder Shock', '30', 'Fighting', NULL, '2', 20, 1, 4, 1),
(90, 'Zapdos', 'Legendary Bird Pokémon from Base Set', 'Thunderstorm', '60', 'Fighting', NULL, '3', 16, 1, 4, 3);
