INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(70, 'Bulbasaur', 'Seed Pokémon from Base Set', 'Vine Whip', '20', 'Fire', NULL, '1', 44, 1, 3, 1),
(80, 'Ivysaur', 'Seed Pokémon from Base Set', 'Razor Leaf', '30', 'Fire', NULL, '2', 30, 1, 3, 2),
(100, 'Venusaur', 'Seed Pokémon from Base Set', 'Solar Beam', '60', 'Fire', NULL, '2', 15, 1, 3, 3),
(60, 'Charmander', 'Lizard Pokémon from Base Set', 'Ember', '30', 'Water', NULL, '1', 46, 1, 1, 1),
(80, 'Charmeleon', 'Flame Pokémon from Base Set', 'Flamethrower', '50', 'Water', NULL, '2', 24, 1, 1, 2),
(120, 'Charizard', 'Flame Pokémon from Base Set', 'Fire Spin', '100', 'Water', NULL, '3', 4, 1, 1, 3),
(60, 'Squirtle', 'Tiny Turtle Pokémon from Base Set', 'Bubble', '20', 'Electric', NULL, '1', 63, 1, 2, 1),
(80, 'Wartortle', 'Turtle Pokémon from Base Set', 'Withdraw', '30', 'Electric', NULL, '1', 42, 1, 2, 2),
(100, 'Blastoise', 'Shellfish Pokémon from Base Set', 'Hydro Pump', '60+', 'Electric', NULL, '3', 2, 1, 2, 3),
(50, 'Caterpie', 'Worm Pokémon from Base Set', 'String Shot', '10', 'Fire', NULL, '1', 45, 1, 3, 1),
(70, 'Metapod', 'Cocoon Pokémon from Base Set', 'Stiffen', '0', 'Fire', NULL, '2', 54, 1, 3, 2),
(90, 'Butterfree', 'Butterfly Pokémon from Jungle', 'Whirlwind', '30', 'Fire', NULL, '1', 33, 2, 3, 3),
(60, 'Oddish', 'Weed Pokémon from Jungle', 'Absorb', '20', 'Fire', NULL, '1', 58, 2, 3, 1),
(70, 'Gloom', 'Weed Pokémon from Jungle', 'Poisonpowder', '30', 'Fire', NULL, '2', 36, 2, 3, 2),
(100, 'Vileplume', 'Flower Pokémon from Jungle', 'Petal Dance', '40x', 'Fire', NULL, '2', 15, 2, 3, 3),
(60, 'Machop', 'Superpower Pokémon from Base Set', 'Low Kick', '20', 'Psychic', NULL, '1', 52, 1, 6, 1),
(80, 'Machoke', 'Superpower Pokémon from Base Set', 'Karate Chop', '50', 'Psychic', NULL, '2', 34, 1, 6, 2),
(100, 'Machamp', 'Superpower Pokémon from Base Set', 'Seismic Toss', '60', 'Psychic', NULL, '3', 8, 1, 6, 3),
(60, 'Gastly', 'Gas Pokémon from Fossil', 'Lick', '10', 'Psychic', NULL, '1', 33, 3, 5, 1),
(80, 'Haunter', 'Gas Pokémon from Fossil', 'Hypnosis', '20', 'Psychic', NULL, '1', 29, 3, 5, 2),
(120, 'Gengar', 'Shadow Pokémon from Fossil', 'Nightmare', '30', 'Darkness', 'Fighting', '2', 5, 3, 5, 3),
(70, 'Onix', 'Rock Snake Pokémon from Base Set', 'Rock Throw', '10', 'Grass', NULL, '3', 56, 1, 6, 1),
(90, 'Geodude', 'Rock Pokémon from Fossil', 'Tackle', '20', 'Grass', NULL, '1', 36, 3, 6, 1),
(100, 'Graveler', 'Rock Pokémon from Fossil', 'Rock Throw', '30', 'Grass', NULL, '2', 37, 3, 6, 2),
(120, 'Golem', 'Megaton Pokémon from Fossil', 'Explosion', '80', 'Grass', NULL, '4', 36, 3, 6, 3),
(60, 'Dratini', 'Dragon Pokémon from Base Set', 'Wrap', '10', 'Ice', NULL, '1', 26, 1, 9, 1),
(80, 'Dragonair', 'Dragon Pokémon from Base Set', 'Slam', '30x', 'Ice', NULL, '2', 18, 1, 9, 2),
(120, 'Dragonite', 'Dragon Pokémon from Fossil', 'Hyper Beam', '40', 'Ice', NULL, '2', 4, 3, 9, 3),
(70, 'Mew', 'New Species Pokémon from Fossil', 'Psywave', '20x', 'Psychic', NULL, '1', 8, 3, 5, 1),
(100, 'Mewtwo', 'Genetic Pokémon from Base Set', 'Psychic', '40+', 'Psychic', NULL, '2', 10, 1, 5, 3);
