INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Sandshrew', 'Mouse Pokémon from Base Set', 'Scratch', '20', 'Water', NULL, '1', 61, 1, 6, 1),
(80, 'Sandslash', 'Mouse Pokémon from Jungle', 'Slash', '30', 'Water', NULL, '2', 31, 2, 6, 2),
(70, 'Nidoran♀', 'Poison Pin Pokémon from Jungle', 'Scratch', '20', 'Psychic', NULL, '1', 57, 2, 3, 1),
(80, 'Nidorina', 'Poison Pin Pokémon from Jungle', 'Double Kick', '30x', 'Psychic', NULL, '2', 40, 2, 3, 2),
(100, 'Nidoqueen', 'Drill Pokémon from Jungle', 'Mega Punch', '50', 'Psychic', NULL, '3', 7, 2, 3, 3),
(70, 'Nidoran♂', 'Poison Pin Pokémon from Base Set', 'Horn Attack', '20', 'Psychic', NULL, '1', 55, 1, 3, 1),
(80, 'Nidorino', 'Poison Pin Pokémon from Base Set', 'Horn Drill', '50', 'Psychic', NULL, '2', 36, 1, 3, 2),
(100, 'Nidoking', 'Drill Pokémon from Base Set', 'Thrash', '60', 'Psychic', NULL, '3', 11, 1, 3, 3),
(60, 'Zubat', 'Bat Pokémon from Fossil', 'Leech Life', '10', 'Electric', NULL, '1', 57, 3, 3, 1),
(80, 'Golbat', 'Bat Pokémon from Fossil', 'Wing Attack', '30', 'Electric', NULL, '2', 25, 3, 3, 2),
(100, 'Crobat', 'Bat Pokémon from Fossil', 'Cross Attack', '30x', 'Electric', NULL, '2', 9, 3, 3, 3),
(70, 'Growlithe', 'Puppy Pokémon from Base Set', 'Flare', '30', 'Water', NULL, '1', 28, 1, 1, 1),
(90, 'Arcanine', 'Legendary Pokémon from Base Set', 'Flamethrower', '50', 'Water', NULL, '2', 23, 1, 1, 2),
(60, 'Poliwag', 'Tadpole Pokémon from Base Set', 'Water Gun', '10+', 'Electric', NULL, '1', 59, 1, 2, 1),
(80, 'Poliwhirl', 'Tadpole Pokémon from Base Set', 'Amnesia', '30', 'Electric', NULL, '2', 36, 1, 2, 2),
(100, 'Poliwrath', 'Tadpole Pokémon from Base Set', 'Submission', '60', 'Electric', NULL, '3', 13, 1, 2, 3),
(60, 'Tentacool', 'Jellyfish Pokémon from Fossil', 'Acid', '10', 'Electric', NULL, '1', 60, 3, 2, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon from Fossil', 'Supersonic', '20', 'Electric', NULL, '2', 43, 3, 2, 2),
(100, 'Staryu', 'Star Shape Pokémon from Base Set', 'Slap', '20', 'Electric', NULL, '1', 64, 1, 2, 1),
(90, 'Starmie', 'Mysterious Pokémon from Base Set', 'Recover', '30', 'Electric', NULL, '2', 35, 1, 2, 2),
(70, 'Magikarp', 'Fish Pokémon from Base Set', 'Splash', '0', 'Electric', NULL, '1', 61, 1, 2, 1),
(100, 'Gyarados', 'Atrocious Pokémon from Base Set', 'Dragon Rage', '50', 'Electric', NULL, '3', 6, 1, 2, 2),
(60, 'Psyduck', 'Duck Pokémon from Fossil', 'Headache', '10', 'Electric', NULL, '1', 53, 3, 2, 1),
(80, 'Golduck', 'Duck Pokémon from Fossil', 'Hyper Beam', '20', 'Electric', NULL, '2', 34, 3, 2, 2),
(70, 'Krabby', 'River Crab Pokémon from Fossil', 'Vice Grip', '10', 'Electric', NULL, '1', 51, 3, 2, 1),
(90, 'Kingler', 'Pincer Pokémon from Fossil', 'Crabhammer', '40', 'Electric', NULL, '2', 34, 3, 2, 2),
(60, 'Horsea', 'Dragon Pokémon from Fossil', 'Smokescreen', '10', 'Electric', NULL, '1', 50, 3, 2, 1),
(80, 'Seadra', 'Dragon Pokémon from Fossil', 'Water Gun', '30+', 'Electric', NULL, '2', 42, 3, 2, 2),
(100, 'Seaking', 'Goldfish Pokémon from Jungle', 'Horn Attack', '30', 'Electric', NULL, '2', 44, 2, 2, 2),
(120, 'Seaking EX', 'Goldfish Pokémon special card', 'Aqua Horn', '60', 'Electric', NULL, '2', 99, 2, 2, 4);
